---
title: "Load data"
author: "Lisa Oshita"
date: "1/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
dir <- file.path(getwd(),"data")

# summary stats of destination countries
countries <- read.csv(file.path(dir, "countries.csv"))
str(countries)
```

#### Age_gender data

```{r}
# AU: Australia, CA: Canada, DE: Germany, ES: Spain, FR: France, 
# GB: United Kingdom, IT: Italy, NL: Netherlands, PT: Portugal
age_gender <- read.csv(file.path(dir, "age_gender_bkts.csv"))
str(age_gender)

# ===========================================================================

# function to plot pop by age range for each country
library(ggplot2)
plot_age <- function(country) {
  ggplot(data = subset(age_gender, country_destination == country), 
         aes(x = age_bucket, y = population_in_thousands, fill = gender)) + 
    geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
    scale_x_discrete("Age Range") + 
    scale_y_continuous("Population (thousands)") + 
    ggtitle(country)
}

ggplot(data = subset(age_gender, country_destination == "AU"), 
       aes(x = reorder(age_bucket), y = population_in_thousands, fill = gender)) + 
  geom_bar(stat = "identity")
purrr::map(as.character(unique(age_gender$country_destination)), ~plot_age(.))

# ===========================================================================

# proportion of males/females visiting each country
library(dplyr); library(magrittr)
age_gender %>% 
  group_by(country_destination) %>%
  summarise(total_pop = sum(population_in_thousands),
            male = sum(population_in_thousands[gender == "male"])/total_pop,
            female = sum(population_in_thousands[gender == "female"])/total_pop) %>% 
  arrange(desc(total_pop))
```

#### train_users data

```{r}
# 213,451 users
train_users <- read.csv(file.path(dir, "train_users_2.csv"))
# converting all factor vars to character
train_users <- dplyr::mutate_if(train_users, is.factor, as.character)

# ===========================================================================

# date account created
# separating year & month of date account created
train_users$dateCreated <- as.Date(train_users$date_account_created, format="%Y-%m-%d")
train_users$yearCreated <- format(train_users$dateCreated, "%Y")
train_users$monthCreated <- format(train_users$dateCreated, "%m")

ggplot(train_users, aes(x = yearCreated, fill = monthCreated)) + 
  geom_histogram(stat = "count") + 
  scale_y_continuous("number accounts created") + 
  scale_x_discrete("year account created") + 
  ggtitle("Number of accounts created per year")

# ===========================================================================

# date first booking
# separating year & month of date of first book 
train_users$firstBook <- as.Date(train_users$date_first_booking, format="%Y-%m-%d")
train_users$firstBookYear <- format(train_users$firstBook, "%Y")
train_users$firstBookMonth <- format(train_users$firstBook, "%m")
```

```{r}
# age 
ggplot(train_users, aes(x = age)) + 
  geom_histogram() + 
  scale_x_continuous(limits = c(0, 100))
median(train_users$age, na.rm = TRUE)
# max age = 2014
# median age = 34
# mean age = 49.7
# 87990 missing ages (41.2%)
```

```{r}
# function to plot bar graphs of categorical vars 
plot_cat <- function(var) {
  ggplot(train_users, aes(x = train_users[[var]])) + 
    geom_bar() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
    ggtitle(var) + 
    scale_x_discrete(var) 
}
# ===========================================================================
# bar plots of all factor vars
factorvars <- c("gender", "signup_method", "language", "affiliate_channel", "affiliate_provider",
                "first_affiliate_tracked", "signup_app", "first_device_type", "country_destination")
purrr::map(factorvars, ~plot_cat(.))
```

```{r}
# missing values 
# function to count + find proportion of missing vals
count_NA <- function(var) {
  if (class(train_users[[var]]) == "numeric") {
      missing <- data.frame(var = var, 
                            total = sum(is.na(train_users[[var]])),
                            proportion = sum(is.na(train_users[[var]])) / nrow(train_users)
                            )
  } else {
    missing <- data.frame(var = var, 
                          total = sum(train_users[[var]] == ""),
                          proportion = sum(train_users[[var]] == "") / nrow(train_users)
                          )
  }
  return(missing)
}
# ===========================================================================
# replacing unknowns with "" in gender var
train_users$gender <- stringr::str_replace(train_users$gender, 
                                           pattern = "-unknown-", 
                                           replacement = "")
# ===========================================================================
purrr::map_df(c("date_first_booking", "gender", "age", "first_affiliate_tracked"), ~count_NA(.))
```




```{r}
# ===========================================================================
# boosting 
# ===========================================================================
library(gbm)

# subset data 
traindat <- subset(train_users, select = c(gender, age, signup_method, signup_flow, signup_app, 
                       affiliate_channel, affiliate_provider, first_affiliate_tracked, 
                       first_device_type, first_browser, country_destination))

# convert character vars to factors (gbm doesn't work with characters)
traindat <- dplyr::mutate_if(traindat, is.character, as.factor)

# fit model 
boostAirbnb <- gbm(country_destination ~ ., data = traindat, 
                   distribution = "multinomial", n.trees = 5, interaction.depth = 4)
# ===========================================================================
# predictions - returns probabilities
predictions <- predict(boostAirbnb, newdata = traindat, n.trees = 5, type = "response")

# assigns predictions to a class
train_users$predictions <- apply(predictions, 1, which.max)
levels <- data.frame(countries = levels(train_users$country_destination), num = 1:12)
train_users$predictions[train_users$predictions == 8] <- "NDF"
train_users$predictions[train_users$predictions == 12] <- "US"

# accuracy 
sum(train_users$predictions == train_users$country_destination) / nrow(train_users)
```





