---
title: "Age_gender & countries"
author: "Lisa Oshita"
date: "1/21/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load data
dir <- file.path(getwd(),"data")
age_gender <- read.csv(file.path(dir, "age_gender_bkts.csv"))
# AU: Australia, CA: Canada, DE: Germany, ES: Spain, FR: France, 
# GB: United Kingdom, IT: Italy, NL: Netherlands, PT: Portugal

countries <- read.csv(file.path(dir, "countries.csv"))
```

#### age_gender 

```{r}
# function to plot population by age range for each country
library(ggplot2)
plot_age <- function(country) {
  ggplot(data = subset(age_gender, country_destination == country), 
         aes(x = age_bucket, y = population_in_thousands, fill = gender)) + 
    geom_bar(stat = "identity") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
    scale_x_discrete("Age Range") + 
    scale_y_continuous("Population (thousands)") + 
    ggtitle(country)
}

(plots <- purrr::map(as.character(unique(age_gender$country_destination)), ~plot_age(.))) 

# age ranges 60-64 decrease in visitation across all countries 
# most number of trips with age groups 20s - early 50s 
```

```{r}
# proportion of males/females visiting each country
library(dplyr); library(magrittr)
age_gender %>% 
  group_by(country_destination) %>%
  summarise(total_pop = sum(population_in_thousands),
            male = sum(population_in_thousands[gender == "male"])/total_pop,
            female = sum(population_in_thousands[gender == "female"])/total_pop) %>% 
  arrange(desc(total_pop))

# higher proportion of females for all countries
```

```{r}
# age range of highest population for each country 
get_maxage <- function(country) {
  m <- age_gender %>% filter(country_destination == country, gender == "male") %>%
    select(age_bucket, population_in_thousands)
  f <- age_gender %>% filter(country_destination == country, gender == "female") %>%
    select(age_bucket, population_in_thousands)
  all <- full_join(m, f, by = "age_bucket")
  all$total <- NA
  for (i in 1:nrow(all)) {
    all$total[i] <- sum(m$population_in_thousands[i], f$population_in_thousands[i])
  }
  return(as.character(all$age_bucket[all$total == max(all$total)]))
}
purrr::map(as.character(unique(age_gender$country_destination)), ~get_maxage(.))
# 1 - AU, 2 - CA, 3 - DE, 4 - ES, 5 - FR, 6 - GB, 7 - IT, 8 - NL, 9 - PT, 10 - US

# Canada has the highest population from 55-59 age group 
# US - highest population from 20-24 age group 
```

#### countries

```{r}
str(countries)
# levenshtein distance: measure of similarity between two strings, greater the distance, the more different the two strings are 
```





