---
title: "Feature Engineering"
author: "Lisa Oshita"
date: "1/28/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load data 
dir <- file.path(getwd(),"data")
age_gender <- read.csv(file.path(dir, "age_gender_bkts.csv"))
countries <- read.csv(file.path(dir, "countries.csv"))
sessions <- read.csv(file.path(dir, "sessionsSample.csv"))
sessions <- sessions[, -1] # removing extra X column 
train_users <- read.csv(file.path(dir, "train_users_2.csv"))
```

```{r}
# converting all factors to character
countries <- dplyr::mutate_if(countries, is.factor, as.character)
sessions <- dplyr::mutate_if(sessions, is.factor, as.character)
train_users <- dplyr::mutate_if(train_users, is.factor, as.character)
```

#### Train_users 

```{r}
# ===========================================================================
# date account created 
# ===========================================================================

train_users$acct_created_date <- as.Date(train_users$date_account_created, format="%Y-%m-%d")

# pulling apart month + year of date created 
train_users$acct_created_y <- format(train_users$acct_created_date, "%Y")
train_users$acct_created_m <- format(train_users$acct_created_date, "%m")

# day of the week
train_users$acct_created_wkd <- weekdays(train_users$acct_created_date)

# season
train_users$acct_created_sn[as.numeric(train_users$acct_created_m) >= 3 & 
                              as.numeric(train_users$acct_created_m) <= 6] <- "spring"
train_users$acct_created_sn[as.numeric(train_users$acct_created_m) >= 7 & 
                              as.numeric(train_users$acct_created_m) <= 9] <- "summer"
train_users$acct_created_sn[as.numeric(train_users$acct_created_m) >= 10 & 
                              as.numeric(train_users$acct_created_m) <= 11] <- "fall"
train_users$acct_created_sn[as.numeric(train_users$acct_created_m) == 12 |  
                              as.numeric(train_users$acct_created_m) <= 2] <- "winter"
```

```{r}
# ===========================================================================
# timestamp first active 
# ===========================================================================

# first active year 
train_users$firstactive_y <- stringr::str_sub(train_users$timestamp_first_active, start = 1, end = 4)

# first active month 
train_users$firstactive_m <- stringr::str_sub(train_users$timestamp_first_active, start = 5, end = 6)

# first active day 
train_users$firstactive_d <- stringr::str_sub(train_users$timestamp_first_active, start = 7, end = 8)

# first active full date 
train_users$firstactive_date <- as.Date(paste(train_users$firstactive_y, "-", 
                                              train_users$firstactive_m, "-", 
                                              train_users$firstactive_d, sep = ""), 
                                        format = "%Y-%m-%d")

# first active weekday 
train_users$firstactive_wkd <- weekdays(train_users$firstactive_date)
```

```{r}
# ===========================================================================
# date first booking
# ===========================================================================

# converting to class = date
train_users$firstbook_date <- as.Date(train_users$date_first_booking, format="%Y-%m-%d")

# pulling apart month + year 
train_users$firstbook_y <- format(train_users$firstbook_date, "%Y")
train_users$firstbook_m <- format(train_users$firstbook_date, "%m")

# day of the week
train_users$firstbook_wkd <- weekdays(train_users$firstbook_date)

# season 
train_users$firstbook_sn[as.numeric(train_users$firstbook_m) >= 3 & 
                              as.numeric(train_users$firstbook_m) <= 6] <- "spring"
train_users$firstbook_sn[as.numeric(train_users$firstbook_m) >= 7 & 
                              as.numeric(train_users$firstbook_m) <= 9] <- "summer"
train_users$firstbook_sn[as.numeric(train_users$firstbook_m) >= 10 & 
                              as.numeric(train_users$firstbook_m) <= 11] <- "fall"
train_users$firstbook_sn[as.numeric(train_users$firstbook_m) == 12 |  
                              as.numeric(train_users$firstbook_m) <= 2] <- "winter"

# indicator variable for if a user booked a trip
train_users$book <- 1
train_users$book[is.na(train_users$firstbook_date)] <- 0
```

```{r}
# ===========================================================================
# age 
# ===========================================================================

# age cleaned 
# leaving users with age 15 - 110 as is 

# for users with ages in the 1900s, ageClean = year account created - age 
train_users$age_clean <- train_users$age
ages <- which(train_users$age > 1000 & train_users$age < 2000)
for (i in ages) {
  train_users$age_clean[i] <- as.numeric(train_users$acct_created_y[i]) - train_users$age[i] 
}

# how to deal with ages > 110 and > 15 and missing values?
# setting all users with ages > 2000 or < 15 as -1
train_users$age_clean[train_users$age < 15 | train_users$age > 110 ] <- -1

# ===========================================================================
# age ranges 

# 18 different age ranges (same as ranges in age_gender df)
train_users$age_bucket <- cut(train_users$age_clean, 
                             breaks = c(0, seq(4, 104, by = 5)), 
                             right = TRUE)
```

```{r}
# ===========================================================================
# gender (female, male, other, missing)
# ===========================================================================

# replacing -unknown- and OTHER with empty string
train_users$gender_clean <- stringr::str_replace(train_users$gender, 
                                           pattern = rebus::or("-unknown-", "OTHER"), 
                                           replacement = "")
```

#### Countries 

```{r}
# ===========================================================================
# merge countries df with train_users 
# ===========================================================================

train_users <- train_users %>% 
    dplyr::full_join(countries, by = "country_destination")
```

#### age_gender 

```{r}
# ===========================================================================
# merge age_gender df with train_users 
# ===========================================================================

# convert gender to lower case to resemble gender in age_gender df
train_users$gender_clean <- stringr::str_to_lower(train_users$gender_clean)

# reformat age_bucket to resemble age_bucket in age_gender
train_users$age_bucket <- as.character(plyr::mapvalues(train_users$age_bucket, 
                                         from = levels(train_users$age_bucket),
                                         to = c("0-4", "5-9", "10-14", "15-19", 
                                                "20-24", "25-29", "30-34", "35-39", 
                                                "40-44", "45-49", "50-54", "55-59",
                                                "60-64", "65-69", "70-74", "75-79", 
                                                "80-84", "85-89", "90-94", "95-99", 
                                                "100+")))

# for df merging: 
age_gender <- dplyr::mutate_if(age_gender, is.factor, as.character)
age_gender$gender_clean <- age_gender$gender

# merging age_gender with train_users according to country
train_users <- train_users %>% left_join(age_gender[, c(1, 2, 4, 6)], 
                                         by = c("country_destination", "age_bucket", "gender_clean"))
```

#### Sessions 

```{r}
# ===========================================================================
# actions (count occurences of actions for each user)
# ===========================================================================

# intialize empty data frame - append counts for each user 
counts <- data.frame(matrix(NA, nrow = 1, 
                            ncol = length(unique(sessions$action)) + 1))
colnames(counts) <- c("id", paste("num", unique(sessions$action), sep = "_"))

# function to count occurences of each type of action for each user 
get_action_counts <- function(user) {
  df <- sessions %>% filter(user_id == user) %>% count(action) # subsetting rows 
  if (ncol(df) <= 2) { 
    df_t <- as.data.frame(data.table::transpose(df))  
    df_t$REMOVE_LATER <- NA # adding extra column (to retain df class)
    colnames(df_t) <- c(paste("num", df$action, sep = "_"), "REMOVE_LATER") # adding column names 
    df_t <- df_t[-1, ] # removing unecessary first row 
  } else {
    df_t <- as.data.frame(data.table::transpose(df))[-1, ] 
    colnames(df_t) <- paste("num", df$action, sep = "_") 
  }
  df_t <- dplyr::mutate_if(df_t, is.character, as.numeric)  
  df_t$id <- user # adding user id column
  return(df_t)
}

# initialize empty list
nums <- list()
unique_users <- unique(sessions$user_id) # iterate over each unique user and append to list 
for(i in 1:length(unique_users)) {
  nums[[i]] <- get_action_counts(unique_users[i])
}
counts <- counts %>% dplyr::bind_rows(nums) # bind dataframes in nums to counts df
counts <- counts[-1, ] # remove first row of NAs
counts <- counts[, -195] # remove REMOVE_LATER column 

# merging counts with train_users
train_users <- train_users %>% full_join(counts, by = "id")
```

```{r}
# ===========================================================================
# action type
# ===========================================================================

type_counts <- data.frame(matrix(NA, nrow = 1, 
                            ncol = length(unique(sessions$action_type)) + 1))
colnames(type_counts) <- c("id", paste("num", unique(sessions$action_type), sep = "_"))

get_type_counts <- function(user, var) {
  df <- sessions %>% filter(user_id == user) %>% count(sessions[[var]]) # subsetting rows 
  if (ncol(df) <= 2) { 
    df_t <- as.data.frame(data.table::transpose(df))  
    df_t$REMOVE_LATER <- NA # adding extra column (to retain df class)
    colnames(df_t) <- c(paste("num", df[1:nrow(df), 1], sep = "_"), "REMOVE_LATER") # adding column names 
    df_t <- df_t[-1, ] # removing unecessary first row 
  } else {
    df_t <- as.data.frame(data.table::transpose(df))[-1, ] 
    colnames(df_t) <- paste("num", df[1:nrow(df), 1], sep = "_") 
  }
  df_t <- dplyr::mutate_if(df_t, is.character, as.numeric)  
  df_t$id <- user # adding user id column
  return(df_t)
}

get_type_counts("zzvatt4dio", var = "action_type") # not working

df <- sessions %>% filter(user_id == "zzvatt4dio") %>% count(action_type)

df
  count(sessions[["action_type"]]) # subsetting rows 
```

```{r}
# ===========================================================================
# action detail (93 different details)
# ===========================================================================
```

```{r}
# ===========================================================================
# device type 
# ===========================================================================
```


```{r}
# ===========================================================================
# one hot encoding (do this last? - once have all vars set up)
# ===========================================================================
library(caret) # for dummyVars funct

# signup_method 
train_users <- cbind(train_users, # combine train_users with data frame of encoded variables 
                     data.frame(predict(dummyVars(" ~ signup_method", data = train_users), 
                                        newdata = train_users)))

# signup_flow
# 17 different levels - condense? 

# language 
train_users <- cbind(train_users, # combine train_users with data frame of encoded variables 
                     data.frame(predict(dummyVars(" ~ language", data = train_users), 
                                        newdata = train_users)))
# ===========================================================================
# function to encode var
encode <- function(var) {
  train_users <- cbind(train_users,
                       data.frame(predict(dummyVars(paste(" ~ ", var, sep = ""), data = train_users), 
                                          newdata = train_users)))
  return(train_users)
}
vars <- colnames(train_users)[10:15] # variables to encode
for(v in vars) { # iterate over each variable, encode, bind to train_users
  train_users <- encode(v)
}
```

