---
title: "Graphics for Final Report/Presentation"
author: "Lisa Oshita"
date: "4/6/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# table with percentages of country_destinations
xtable::xtable(df)
```

```{r}
# histogram of user's ages 
age_df <- train_users %>% select(country_destination, age_clean) %>% filter(age_clean > 0)
ggplot(data = age_df, aes(x = age_clean)) + 
  geom_histogram(bins = 20, alpha = 0.75) + 
  scale_x_continuous(limits = c(0, 100)) + 
  theme_minimal() + 
  xlab("Age") + ylab("Count") + ggtitle("Histogram of User's Ages")

ggsave(filename = "ages_histogram.pdf", plot = last_plot(), width = 8, height = 5)
```


```{r}
# bar chart of genders and country destinations 
genderdf <- train_users %>% select(country_destination, gender_clean) %>% filter(gender_clean != "unknown")

formatter <- function(x) {
  round(x / 117481, 2)
}

ggplot(data = genderdf, aes(x = forcats::fct_infreq(country_destination), fill = gender_clean)) + 
  geom_bar(position = "dodge") + 
  scale_fill_discrete(name = "Gender", labels = c("Female", "Male")) + 
  scale_y_continuous(labels = formatter) + 
  ylab("Proportion") + 
  xlab("Destination") + 
  ggtitle("Gender Preferences for Booking Destinations")

ggsave(filename = "gender_visual.pdf", plot = last_plot(), width = 8, height = 5)
```

```{r}
# time series plot of date first book 
firstbookDate <- train_users %>% select(date_first_booking) %>% filter(date_first_booking != "")

firstbookDF <- data.frame(date = names(table(firstbookDate$date_first_booking)),
                          count = unname(table(firstbookDate$date_first_booking)))

firstbookDF$date <- as.Date(firstbookDF$date, format="%Y-%m-%d")

ggplot(firstbookDF, aes(x = date, y = count.Freq)) + 
  geom_point() + 
  geom_smooth() + 
  scale_x_date(date_breaks = "3 months") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  ylab("Count") + xlab("Date") + 
  ggtitle("Number of bookings made over time")

ggsave("bookingsovertime.pdf", plot = last_plot(), width = 8, height = 5)
```

```{r}
# number of accounts created per year, separated by month 
ggplot(train_users, aes(x = acct_created_y, fill = acct_created_m)) + 
  geom_histogram(stat = "count") + 
  scale_y_continuous("Number of Accounts Created") + 
  scale_x_discrete("Year") + 
  ggtitle("Number of accounts created per year") + 
  scale_fill_discrete(name = "Month")

# only have data for up to June 
# shows huge increase in users creating Airbnb accounts each year 

ggsave("accountscreated.pdf", plot = last_plot(), width = 8, height = 5)
```



```{r}
xtable::xtable(table(sampled_predsdf_xgb$max_prob, sampled_predsdf_xgb$label))
```


```{r}
xtable::xtable(table(stacked_predsdf1$max_prob, stacked_predsdf1$label))
```

```{r}
# feature importance 
# random forest
xtable::xtable(feature_imp_df[1:20, ])
xtable::xtable(importance[1:20, ])
```

```{r}
table <- as.data.frame(table(training$country_destination))
colnames(table) <- c("Destination", "Frequency")

ggplot(data = table, aes(x = factor(1), y = Frequency, fill = Destination)) + 
  geom_bar(width = 1, stat = "identity") + 
  coord_polar(theta = "y") + 
  ylab("") + xlab("") + 
  ggtitle("Pie Chart of Booking Destinations") +
  theme(text = element_text(size = 25),
        axis.text = element_blank())

ggsave(filename = "pie_chart_dest.pdf", width = 8, height = 7)
```






